[package]
name = "ohkami_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
ohkami_macros = { version = "0.2", path = "../ohkami_macros" }

# tokio = { optional = true, version = "", features = ["full"] }
async-std = { optional = true, version = "1" }

[features]
default = ["async-std"]

# tokio = ["dep:tokio"]
async-std = ["dep:async-std"]
# lunatic = []
