[package]
name = "ohkami"
version = "0.2.0"
edition = "2021"
authors = ["kanarus <kanarus786@gmail.com>"]
description = "simple and non macro-based web framework"
documentation = "https://docs.rs/ohkami/"
homepage = "https://crates.io/crates/ohkami"
repository = "https://github.com/kana-rus/ohkami"
readme = "README.md"
keywords = ["simple", "async", "web", "server"]
categories = ["web-programming::http-server"]
license = "MIT"

[dependencies]
sqlx = { version = "0.6", default-features = false, optional = true }
serde = "1.0"
serde_json = "1.0"
chrono = "0.4"
async-std = "1"
tracing = "0.1"
tracing-subscriber = "0.3"

[features]
default  = []
sqlx     = ["dep:sqlx"]
postgres = ["sqlx?/runtime-async-std-native-tls", "sqlx?/postgres"]
mysql    = ["sqlx?/runtime-async-std-native-tls", "sqlx?/mysql"]