# [workspace]
# members = [
#     ".",
#     "examples/simple",
# ]

[package]
name = "ohkami"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.6", default-features = false, optional = true }
serde = "1.0"
serde_json = "1.0"
chrono = "0.4"
async-std = "1"
tracing = "0.1"
tracing-subscriber = "0.3"

[features]
default  = []
# default = ["sqlx", "postgres"] # for debugging

sqlx     = ["dep:sqlx"]
postgres = ["sqlx?/runtime-async-std-native-tls", "sqlx?/postgres"]
mysql    = ["sqlx?/runtime-async-std-native-tls", "sqlx?/mysql"]