[workspace]
members = [
    "ohkami",
    "ohkami_macros",
]
exclude = [
    "examples/db",
    "examples/react_todo",
    "simple",
    "static_file",
    "techempower",
    "use_middleware",
    "with_test"
]
