[workspace]
members = [
    ".",
    "examples/db",
]

[package]
name = "ohkami"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.6", default-feature = false , optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
futures = "0.3"
async-std = "1"

[features]
default  = []
postgres = ["sqlx?/postgres"]
mysql    = ["sqlx?/mysql"]