[package]
name = "ohkami"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.6", features = ["runtime-async-std-native-tls", "postgres"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
futures = "0.3"
async-std = "1"

[dev-dependencies]
once_cell = "1.16.0"

[features]
default  = []
postgres = []
mysql    = []