[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
ohkami = { git = "https://github.com/kana-rus/ohkami" }
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.16.0"