[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
ohkami = { path = "./ohkami", features = ["sqlx", "postgres"] }
serde = "1.0"
sqlx = "0.6"
once_cell = "1.16.0"
# tracing = "0.1"
# tracing-subscriber = "0.3"