version: '3'

services:
  server:
    container_name: server
    tty: true
    env_file:
      - ./.env
    ports:
      - 3000:3000
    depends_on:
      - db
    build:
      context: ../..
      dockerfile: ./examples/db/Dockerfile

  db:
    env_file:
      - ./.env
    image: postgres:15.1-alpine
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local