[package]
name = "ohkami"
version = "0.9.0"
edition = "2021"
authors = ["kanarus <kanarus786@gmail.com>"]
description = "ergonomic and macro free web framework"
documentation = "https://docs.rs/ohkami/"
homepage = "https://crates.io/crates/ohkami"
repository = "https://github.com/kana-rus/ohkami"
readme = "../README.md"
keywords = ["simple", "async", "web", "server", "framework"]
categories = ["web-programming::http-server"]
license = "MIT"

[dependencies]
ohkami_macros = { version = "0.2", path = "../ohkami_macros" }

tokio = { optional = true, version = "1", features = ["net", "rt", "io-util"] }
async-std = { optional = true, version = "1" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
percent-encoding = "2.2.0"

[features]
rt_tokio = ["dep:tokio"]
rt_async-std = ["dep:async-std"]

##### DEBUG #####
# default = ["rt_tokio"]
