[package]
name           = "ohkami"
version        = "0.11.0"
edition        = "2021"
authors        = ["kanarus <kanarus786@gmail.com>"]
description    = "declarative web framework for Rust"
documentation  = "https://docs.rs/ohkami"
homepage       = "https://crates.io/crates/ohkami"
repository     = "https://github.com/kana-rus/ohkami"
readme         = "../README.md"
keywords       = ["declarative", "async", "web", "server", "framework"]
categories     = ["asynchronous", "web-programming::http-server"]
license        = "MIT"

[package.metadata.docs.rs]
features       = ["rt_tokio", "custom-header"]
rustdoc-args   = ["--no-deps"]

[dependencies]
ohkami_macros  = { version = "0.5", optional = true, path = "../ohkami_macros" }
tokio          = { version = "1",   optional = true, features = ["net", "rt", "io-util", "sync"] }
async-std      = { version = "1",   optional = true }
byte_reader    = { version = "1.2.2", features = ["text"] }
serde          = "1.0"
serde_json     = "1.0"
sha1           = { version = "=0.11.0-pre.0", optional = true, default-features = false }
sha2           = { version = "=0.11.0-pre.0", optional = true, default-features = false }
hmac           = { version = "=0.13.0-pre.0", optional = true, default-features = false }
rustc-hash     = { version = "1.1", optional = true }

[features]
default        = ["utils", "testing"]
rt_tokio       = ["dep:tokio"]
rt_async-std   = ["dep:async-std"]
utils          = ["dep:ohkami_macros", "dep:sha2", "dep:hmac"]
testing        = []
custom-header  = ["dep:rustc-hash"]
#websocket     = ["dep:sha1"]
#sse           = []

##### DEBUG #####
DEBUG = [
    "serde/derive",
    "tokio?/macros",
    "tokio?/rt-multi-thread",
    "async-std?/attributes",
]
#default = [
#    "utils",
#    "testing",
#    "custom-header",
#    #"websocket",
#    "rt_tokio",
#    #"rt_async-std",
#    "DEBUG",
#]