[package]
name = "ohkami"
version = "0.9.0"
edition = "2021"
authors = ["kanarus <kanarus786@gmail.com>"]
description = "simple and macro free web framework"
documentation = "https://docs.rs/ohkami/"
homepage = "https://crates.io/crates/ohkami"
repository = "https://github.com/kana-rus/ohkami"
readme = "../README.md"
keywords = ["simple", "async", "web", "server", "framework"]
categories = ["web-programming::http-server"]
license = "MIT"

[dependencies]
ohkami_macros = { version = "0.2", path = "../ohkami_macros" }
ohkami_lib = { version = "0.1", path = "../ohkami_lib" }

# tokio = { optional = true, version = "", features = ["full"] }
async-std = { optional = true, version = "1" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
fxhash = "0.2"
tracing = "0.1"
tracing-subscriber = "0.3"
once_cell = "1.17"

[features]
default = ["async-std"]

# tokio = ["dep:tokio"]
async-std = ["dep:async-std"]
# lunatic = []
