[package]
name = "ohkami"
version = "0.7.0"
edition = "2021"
authors = ["kanarus <kanarus786@gmail.com>"]
description = "simple and macro free web framework"
documentation = "https://docs.rs/ohkami/"
homepage = "https://crates.io/crates/ohkami"
repository = "https://github.com/kana-rus/ohkami"
readme = "https://github.com/kana-rus/ohkami/blob/main/README.md"
keywords = ["simple", "async", "web", "server", "framework"]
categories = ["web-programming::http-server"]
license = "MIT"

[dependencies]
ohkami_macros = { version = "0.1.0", path = "../ohkami_macros" }
sqlx = { version = "0.6", default-features = false, optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
async-std = "1"
tracing = "0.1"
tracing-subscriber = "0.3"

[features]
default  = []
sqlx     = ["dep:sqlx"]
postgres = ["sqlx?/runtime-async-std-native-tls", "sqlx?/postgres"]
mysql    = ["sqlx?/runtime-async-std-native-tls", "sqlx?/mysql"]