version: '3'

services:
  db:
    env_file:
      - ./.env
    image: postgres:15.1-alpine
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      # start_period: 30s

volumes:
  data:
    driver: local