[workspace]
resolver = "2"
members  = [
    "form",
    "hello",
    "realworld",
    "quick_start",
]

[workspace.dependencies]
ohkami             = { version = "0.13.0", path = "../ohkami", features = ["rt_tokio"] }
tokio              = { version = "1", features = ["full"] }
serde              = { version = "1", features = ["derive"] }
sqlx               = { version = "0.7.3", features = ["runtime-tokio-native-tls", "postgres", "macros", "chrono", "uuid"] }
tracing            = "0.1"
tracing-subscriber = "0.3"
chrono             = "0.4"