[workspace]
resolver = "2"
members  = [
    "form",
    "hello",
    "quick_start",
]

[workspace.dependencies]
ohkami = { version = "0.10", path = "../ohkami", default-features = false, features = ["rt_tokio"] }
tokio  = { version = "1", features = ["full"] }
serde  = { version = "1", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
