[lib]
proc-macro = true

[package]
name        = "ohkami_macros"
version     = "0.2.0"
edition     = "2021"
authors     = ["kanarus <kanarus786@gmail.com>"]
description = "proc macros for ohkami web framework"
keywords    = ["ohkami", "web", "framework", "macro"]
categories  = ["rust-patterns"]
license     = "MIT"

[dependencies]
proc-macro2 = "1.0"
quote       = "1.0"
syn         = { version = "1.0", features = ["full"] }
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
