name: check
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [db, simple, static_file, techempower, with_test, use_middleware]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: run check
        run: |
          cd ./examples/${{ matrix.example }}
          cargo check