name: check
on:
  pull_request:
  push:
      branches:
        - main

jobs:
  cargo-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rt: [tokio, async-std]

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile:   minimal
          override:  true

      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features rt_${{ matrix.rt }}
