name: test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-stable:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rt: [tokio, async-std]

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile:   minimal
          override:  true

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features rt_${{ matrix.rt }},DEBUG

  test-nightly:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rt: [tokio, async-std]

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile:   minimal
          override:  true

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features nightly,rt_${{ matrix.rt }},DEBUG