name: test
on: [pull_request]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile:   minimal
          override:  true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --lib --features rt_async-std
