[package]
name = "simple"
version = "0.1.0"
edition = "2021"

[dependencies]
ohkami = { path = "../../" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"